.TH COLLATINUS 1 "septembre  9, 2003"
.SH NAME
collatinus \- programma ad latinam morphologiam et lemmata extrahenda
.SH SYNOPSIS
.B collatinus
.SH DESCRIPTION
\fBcollatinus\fP programma est quod, latino texto dato, omnibus lemmatibus
omnium uerborum extractis, dare potest casum, numerum, generum, personam,
tempus, modum et uocem uniuscuiusque eorum. Utile est magistro qui uult
discipulos suos studere textis qui non in eorum libro sunt.
.br
Si uis amplius auxilium legere, potes hic ire : 
/usr/share/collatinus/doc/index.html
.SH OPTIONS
nulla optio. Omnia graphice fiunt.
.SH AUTHOR
Haec manualis pagina scripta est ab Iuono Ouvrard. Vale.


